### ISSUE TITLE
Chapter titles should be all caps

### ISSUE THREAD

**Issue by jcwhittier** [rpspringuel/maine-thesis#16]
The `chapterhead` portion of chapter titles should be capitalized. For example, **Chapter 1** should be replaced with **CHAPTER 1**. The table of contents should still list chapters under the heading **Chapter**

This could be fixed in`maine-thesis.cls` by replacing `\renewcommand*\chaptername{Chapter}` with`\renewcommand*\chaptername{CHAPTER}` and `\toclabel{\chaptername}` with `\toclabel{Chapter}`.

**Comment by jcwhittier** [comment]
I opened the pull request #17 to address this issue

**Comment by rpspringuel** [comment]
Addressed in 54d4ed9545fac0c96c377bd79630eb781cca1df6
