### ISSUE TITLE
Extra space added between sections

### ISSUE THREAD

**Issue by jcwhittier** [rpspringuel/maine-thesis#21]
In the LaTeX template additional spacing is added between sections that is different from the Grad School Word template

LaTeX:
<img width="616" alt="sectionspacing" src="https://user-images.githubusercontent.com/2036365/47100681-180de280-d206-11e8-8e46-6e048d940c8d.png">

Word:
<img width="616" alt="sectionspacingword" src="https://user-images.githubusercontent.com/2036365/47100915-a5513700-d206-11e8-8379-43992c6e9b35.png">

**Comment by rpspringuel** [comment]
I can check those distances, but please make sure its not just LaTeX stretching the space to make the bottom of the page flush first.  The spaces between sections (or subsections or subsubsections) are inherently stretchy in LaTeX so that it can maintain a nice and level bottom line.

**Comment by jcwhittier** [comment]
The additional spacing happens throughout. I'm checking with the Grad School on the requirements. It's not clear whether all additional vertical spacing around headings, equations, tables, figures, lists, etc. is prohibited. 

<img width="614" alt="screen shot 2018-10-18 at 11 50 03 am" src="https://user-images.githubusercontent.com/2036365/47170532-3cd08b80-d2d4-11e8-9212-4afbf7334c75.png">

**Comment by jcwhittier** [comment]
Having not heard back from the Grad School with specific spacing requirements, I'm closing this issue for now. I will reopen this issue if it seems that the `maine-thesis.cls` class file does not comply with the spacing requirements.
